### ISSUE TITLE
Installtion

### ISSUE THREAD

**Issue by ag35** [ag35/SEBC#1]
stuff about /usr/share/cmf/schema/scm_prepare_database.sh 

https://www.cloudera.com/documentation/enterprise/5-6-x/topics/cm_ig_installing_configuring_dbs.html#concept_i2r_m3m_hn__section_qjj_pyp_bm

**Comment by ag35** [comment]
Started CDH install - yey!!!

**Comment by ag35** [comment]
For some reason CM pushes MySQL 5.1 install which makes the installation fail since we already have MySQL 5.5 installed. Is there a way to remove mysql from the repository?

**Comment by ag35** [comment]
Reinstalled mysql using repos. CLouder manager server is up and running, moving on to CDH install

**Comment by ag35** [comment]
Done with CDH setup!

**Comment by mfernest** [comment]
It's not the CM repo that pushes MySQL 5.1, it the Centos/RHEL default repositories. You can verify this with yum if you're interested. This is why it's important to grab the repo from dev.mysql.com.

**Comment by mfernest** [comment]
Completed
