### ISSUE TITLE
HUE Lab: Authenticate using Linux users/groups

### ISSUE THREAD

**Issue by ag35** [ag35/SEBC#11]
1. Make sure MySQL is prepared for Hue:
show global VARIABLES like 'sql_mode';

Set it if empty:
mysql> set global sql_mode=STRICT_ALL_TABLES;
Query OK, 0 rows affected (0.00 sec)

Add to /etc/my.cnf file under [mysqld] so that it will stay during next restart

2. Add Oozie service to cluster, install it
3. Add hue next
3. Add HttpFs role to HDFS (if not added before), make sure Hue is pointed to HttpFs and restart the services

**Comment by ag35** [comment]
Follow this to import OS users to Hue
http://gethue.com/hadoop-tutorial-how-to-integrate-unix-users-and-groups/

**Comment by ag35** [comment]
Stuck!!! While trying to export linux users into HUE

export JAVA_HOME=/usr/java/jdk1.7.0_67-cloudera/
/opt/cloudera/parcels/CDH/lib/hue/build/env/bin/hue useradmin_sync_with_unix
subprocess.CalledProcessError: Command '/var/run/cloudera-scm-agent/process/423-hue-HUE_SERVER/altscript.sh sec-5-password' returned non-zero exit status 1
[root@ip-172-31-56-250 423-hue-HUE_SERVER]# /var/run/cloudera-scm-agent/process/423-hue-HUE_SERVER/altscript.sh sec-5-password
Error: Password not present

**Comment by ag35** [comment]
This is finally solved it!

# Directory for the last Hue service startup
export HUE_CONF_DIR="/var/run/cloudera-scm-agent/process/423-hue-HUE_SERVER"
#Make sure JAVA_HOME is set, and do not get surprized....
# Hue ADMIN password
export HUE_SECRET_KEY=Cloudera
#Hue Mysql database password
 export HUE_DATABASE_PASSWORD=oozie
#Finally 
 export HUE_IGNORE_PASSWORD_SCRIPT_ERRORS=1

# Finally try it
/opt/cloudera/parcels/CDH/lib/hue/build/env/bin/hue useradmin_sync_with_unix

**Comment by mfernest** [comment]
Nice recovery!

**Comment by ag35** [comment]
Thanks, but now we have passwords exposure ...
