### ISSUE TITLE
Install MySQL

### ISSUE THREAD

**Issue by ag35** [ag35/SEBC#14]

**Comment by ag35** [comment]
added to my.cnf for HUE so that I do not have to adjust it in the future ...
sql_mode=STRICT_ALL_TABLES;

**Comment by ag35** [comment]
Got STUCK ... with mysql will not start. trying the following 

Uninstall mysql using yum remove mysql*
Recursively delete /usr/bin/mysql and /var/lib/mysql
Delete the file /etc/my.cnf.rmp
Use ps -e to check the processes to make sure mysql isn't still running.
Reboot server with reboot
Run yum install mysql-server. This also seems to install the mysql client as a dependency.
Give mysql ownership and group priveleges with:

chown -R mysql /var/lib/mysql

chgrp -R mysql /var/lib/mysql
Use service mysqld start to start MySQL Daemon.

**Comment by ag35** [comment]
And that worked!!!

**Comment by mikeridley** [comment]
Looks good.
