### ISSUE TITLE
HDFS Lab: Replicate to another cluster

### ISSUE THREAD

**Issue by ag35** [ag35/SEBC#5]

**Comment by ag35** [comment]
1. Create source and target directories in HDFS
2. Created a peer in CM: Jerry_Anderson, 75.101.204.230:7180
3. Tested connectivity
4. Created a scheduel: source: /jerry-anderson/ , target /user/ec2-user/jerry_anderson_SEBC , schedule immediate
5. The replication failed since the peer is not local to my cluster

**Comment by mfernest** [comment]
Completed
