### ISSUE TITLE
YARN/RM Lab: Tuning for YARN

### ISSUE THREAD

**Issue by ag35** [ag35/SEBC#8]

**Comment by ag35** [comment]
Done, but noticed no performance improvements.

**Comment by mfernest** [comment]
Hm... did you adjust the number of records in the test script to the correct amount (100,000,000)?

**Comment by ag35** [comment]
I did, but still did not see much differences. I did not have a chance (enough time) to play with container size. I'm pretty much sure I could have noticed the difference.
